"""phionyx-compliance — evidence-grade compliance report draft generator.

DISCIPLINE: Reports produced by this package are *evidence-oriented
mappings*, NOT certifications. Every rendered report carries the
canonical disclaimer at the head AND tail.

Public surface (v0.1):

  - __version__                       : str       package version
  - CANONICAL_DISCLAIMER_HEAD          : str       head disclaimer (every report)
  - CANONICAL_DISCLAIMER_TAIL          : str       tail disclaimer (every report)
  - load_template(name)                : Template  load by name
  - list_templates()                   : list[str] available templates on disk
  - render(template, inputs)           : str       render → markdown
  - sample_inputs(template_name)       : dict      synthetic inputs for the template
"""
from __future__ import annotations

__version__ = "0.1.0a1.dev0"


# ── Canonical disclaimers ──────────────────────────────────────────
# Wired into every template render. Changing this text changes the
# disclaimer on every report; do not change without founder + legal
# review.

CANONICAL_DISCLAIMER_HEAD = (
    "**Evidence-oriented mapping — not a legal compliance guarantee.** "
    "This draft is generated by `phionyx-compliance` from a Phionyx "
    "runtime evidence chain. It is structured against the framework's "
    "obligations but does NOT certify compliance. A lawyer or qualified "
    "auditor must review before any use that implies legal posture. "
    "Phionyx produces evidence chains; certifications are the operator's "
    "and the auditor's joint responsibility."
)

CANONICAL_DISCLAIMER_TAIL = (
    "**Reminder.** Reports produced by `phionyx-compliance` are evidence-"
    "oriented mappings, not legal compliance guarantees. A qualified "
    "auditor must review this draft. The runtime evidence chain it is "
    "structured against is independently verifiable; the chain alone is "
    "not sufficient to establish compliance with the framework cited."
)


# ── Public API surface (lazy imports to keep import cost low) ─────

from .templates import Template, list_templates, load_template  # noqa: E402
from .renderer import render, sample_inputs  # noqa: E402
from .chain_view import ChainView, VerifyResult, find_traces  # noqa: E402
from .mapping import resolve_inputs  # noqa: E402

__all__ = [
    "__version__",
    "CANONICAL_DISCLAIMER_HEAD",
    "CANONICAL_DISCLAIMER_TAIL",
    "Template",
    "list_templates",
    "load_template",
    "render",
    "sample_inputs",
    "ChainView",
    "VerifyResult",
    "find_traces",
    "resolve_inputs",
]
